name 'base'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'All Rights Reserved'
description 'Installs/Configures base'
version '0.1.0'
chef_version '>= 15.0'

depends 'apt'
depends 'auditd'
