version: '3'

services:
  app:
    build: .
    ports:
      - 8000:8000
    command: ["go", "run", "/main.go"]
  proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
