# frozen_string_literal: true

# -*- mode: ruby -*-
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/groovy64"

  def define_machine_name(c, name)
    c.vm.provider :virtualbox do |vbox|
      vbox.name = name
    end
  end

  config.vm.define :ubuntu do |c|
    define_machine_name c, "ubuntu"
  end
end
